### ISSUE TITLE
ventilation comptable / liens 

### ISSUE THREAD

**Issue by oscim** [Darkjeff/dolibarr_ventilation_compta#107]
Bonjour, 

Sur la page de ventilation ( index.php dans customer / supplier ), j'ai ajouté un liens dans chaque la colonne des numero de compte compta pour chaque lignes, afin de rendre plus simple le controle comme suit: 

dans le tableau de ventilation comptable annuel 
<code>
    while ($i < $num)
    {
        $row = $db->fetch_row($resql);
//      print '<tr><td width=60>'.$row[0].'</td>';
      print '<tr><td width=60> <a href="lignes.php?search_account='.$row[0].'">'.$row[0].'</a></td>';
</code>
Il deviens plus simple de naviguer

**Comment by Darkjeff** [comment]
Merci de me contacter pour intégrer ce code
