### ISSUE TITLE
Table llx_c_pays does not exist

### ISSUE THREAD

**Issue by jpfox** [Darkjeff/dolibarr_ventilation_compta#110]
I encounter an error in menu "Paramètres" "Comptes tiers".

I use Dolibarr 3.7.0 and accountingex branch 3.6

Dolibarr a détecté une erreur technique.
You use an experimental or develop level of features, so please do NOT report any bugs, except if problem is confirmed moving option MAIN_FEATURES_LEVEL back to 0.
Voici les informations qui pourront aider au diagnostic:
Date: 20150423104800
Dolibarr: 3.7.0
Niveau de fonctionnalités: 1
PHP: 5.6.7-1
Server: Apache/2.4.10 (Debian)
OS: Linux dolibarr 3.16.0-4-586 #1 Debian 3.16.7-ckt9-2 (2015-04-13) i686
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0

Url sollicitée: /custom/accountingex/admin/thirdpartyaccount.php?idmenu=23
Referer: http://192.168.158.77/custom/accountingex/admin/productaccount.php?idmenu=24
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: (SELECT s.rowid, s.nom as name , s.address, s.zip , s.town, s.code_compta as compta , s.fk_forme_juridique , s.fk_pays , s.phone , s.fax , f.datec , f.fk_soc , cp.libelle as country FROM llx_societe as s, llx_facture as f, llx_c_pays as cp WHERE f.fk_soc = s.rowid AND s.fk_pays = cp.rowid AND f.datec >= '20140701000000' AND f.datec <= '20150630235959' AND f.entity = 1 GROUP BY name)UNION (SELECT s.rowid, s.nom as name , s.address, s.zip , s.town, s.code_compta_fournisseur as compta , s.fk_forme_juridique , s.fk_pays , s.phone , s.fax , ff.datec , ff.fk_soc , cp.libelle as country FROM llx_societe as s, llx_facture_fourn as ff, llx_c_pays as cp WHERE ff.fk_soc = s.rowid AND s.fk_pays = cp.rowid AND ff.datec >= '20140701000000' AND ff.datec <= '20150630235959' AND ff.entity = 1 GROUP BY name)ORDER BY name ASC
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHTABLE
Information sur le dernier accès en base en erreur: Table 'dolibarr.llx_c_pays' doesn't exist

**Comment by jpfox** [comment]
It is necessary to change llx_c_pays to llx_c_country and cp.libelle to cp.label in this request

**Comment by aspangaro** [comment]
Hi @jpfox 

The module isn't maintened for the version 3.7.0 of Dolibarr because it's already included in the core of Dolibarr.
The module is under developement status but it's present with a lot of amelioration.

**Comment by jpfox** [comment]
Merci pour la réponse rapide.
Je ne comprends pas, il manque pas mal de choses si on n'installe pas ce module : plan comptable, export, ventilation... ? Est-ce bien dans la branche 3.7 du coeur ?

**Comment by Darkjeff** [comment]
You must change the value for MAIN_FEATURES_LEVEL to "2" (in order to have experimental modul)

**Comment by jpfox** [comment]
Thank you for this clear answer.
