### ISSUE TITLE
Dolibarr 3.8

### ISSUE THREAD

**Issue by caBBAlainB** [Darkjeff/dolibarr_ventilation_compta#111]
Bonjour,
Est-ce que ce module est compatible avec la version 3.8?

**Comment by aspangaro** [comment]
Bonjour,

Non ce module n'est je pense plus compatible avec la version 3.8 de dolibarr. Une version intégré au core existe dans dolibarr depuis la version 3.7. Il faut passer en mode développeur (Main_feature à 2 dans divers) et activé le module comptabilité avancé
