### ISSUE TITLE
Erreur de compte!

### ISSUE THREAD

**Issue by caBBAlainB** [Darkjeff/dolibarr_ventilation_compta#112]
Bonjour,
Je suis surpris, je n'ai pas vérifié tout votre plan comptable mais l'un des premiers que je reargde, le 604, correspond pour vous à Achats stockés - Matières premières (et fournitures) alors que d'après mes diverses recherches sur internet, ce serait plutôt Achats d'études et prestations de services

**Comment by aspangaro** [comment]
Vous utilisez quel plan comptable ?

Sinon je vends sur le dolistore le nouveau plan comptable PCG 2014 developpé :
https://www.dolistore.com/fr/themes/523-Plan-comptable-Fran--ais-2014-complet-d--velopp--.html?search_query=plan&results=7
