### ISSUE TITLE
Problème de ventilation achat

### ISSUE THREAD

**Issue by caBBAlainB** [Darkjeff/dolibarr_ventilation_compta#113]
J'ai un service affecté au compte compta 651002.
Hors lorsque je crée une facture, l'achat est affecté au compte par défaut 604000 
Pourquoi?

**Comment by aspangaro** [comment]
Le module n'étant pas compatible avec la version 3.8. Je ne saurai vous répondre...

Essayez d'utiliser la version dans le core
