### ISSUE TITLE
Suivi

### ISSUE THREAD

**Issue by sebastienserre** [Darkjeff/dolibarr_ventilation_compta#114]
Bonsoir,
Ce module est il toujours maintenu?
Est il fonctionnel pour Dolibarr 3.9 ?

**Comment by Darkjeff** [comment]
Ce module est maintenant intégré au core de dolibarr 
le manuel est disponible ici : 
http://www.jeffinfo.com/comptabilite-dolibarr-participer/

**Comment by sebastienserre** [comment]
Bien je suis désolé, mais je ne vois pas ou activer les fonctions de comptabilité...

**Comment by Darkjeff** [comment]
normalement tout est expliqué dans le manuel en pdf qu'on peut télécharger sur la page précédente
mais voici un tuto en image 
http://www.jeffinfo.com/comptabilite-dolibarr/
