### ISSUE TITLE
préfixe table bdd

### ISSUE THREAD

**Issue by ginux** [Darkjeff/dolibarr_ventilation_compta#46]
Bonjour, j'ai utilisé ce module et vous remercie pour votre travail.
Un petit bug que j'ai relevé. J'ai modifié le préfixe de mes tables dans la bdd lors de l'install de Dolibarr. Lorsque je demande la balance mensuelle de votre module, ceci me déclenche une erreur , ne trouvant pas une table "llx_..."
J'ai vu dans votre code que vous faisiez bien appel à cette variable de préfixe dans le conf.php mais sans doute doit-il rester des traces de "llx" dans certains codes. J'ai renommé mes tables avec le suffixe "llx", tout fonctionne parfaitement.
Encore merci pour votre code.

**Comment by aspangaro** [comment]
Bonjour,

Je viens de vérifier toutes les pages du module et j'ai effectivement trouvé un prefix de bdd en dur dans la page balance mensuelle. Le commit suivant devrait régler le problème : 

https://github.com/Darkjeff/dolibarr_ventilation_compta/pull/47

Bonne journée.

**Comment by ginux** [comment]
Merci à vous. De mon côté, j'ai déjà rebaptisé les tables de la bdd. Cela
servira aux prochains.
Bonen journée.

## 

Gilles Naudy
Tel : 06 77 97 23 37
