### ISSUE TITLE
Ventes et achats à l'étranger

### ISSUE THREAD

**Issue by BebZ** [Darkjeff/dolibarr_ventilation_compta#49]
Bonjour, 

Comment faire la différence entre ventes en France et ventes à l'étranger, les codes TVA ne devraient pas être les mêmes et la TVA devrait "s'auto liquider" seulement dans les fiches produits on ne renseigne qu'un seul code de TVA (vente et achats) il devrait y avoir un cas prévu pour ventes et achats étranger, non ?

Ceci pour entrer dans les règles fiscales de l'administration je pense...
TVA VENTES MARCHANDISES
TVA VENTES MARCHANDISES CEE
etc... 

Jeff m'a parlé d'un script, quel pourrait-il être ?

**Comment by aspangaro** [comment]
Bonjour,

(Hubz ?)

Il n'y a aujourd'hui je pense aucune solution valable...

J'ai le cas pour un client mais avec des ventes à l'étranger plus que limité (10-11 factures par ans) Au-delà de créer un compte de vente spécifique (à 0%) et ensuite je rectifie à la main les écritures dans mon logiciel une fois l'export effectué pour rajouter les comptes de TVA pour l’auto-liquidation.

Le problème dans le fonctionnement actuel du module et que même en créant un taux spécifique, il est fait pour des écritures comptable de 3 lignes ou deux mais pas 4 comprenant au débit et au crédit un compte de TVA.

Je vais essayer de regarder rapidement ce point.

Par contre, je n'ai pas connaissance d'un script quelconque.

Bonne journée,

**Comment by BebZ** [comment]
Oups. Qu'est ce que cela implique alors je ne peux pas faire de solde de tva a la fin du mois le 20 et le declarer?
Donc pour un comptable avec une mission de révision simolement limport classique n'est pas possible? 
Y a t il dautres implications?

**Comment by Darkjeff** [comment]
Pas possible de rajouter l'écriture dans les journaux effectué sur les table de vente ou d'achat 

mais dans bookkeeping on peut rajouter des écritures manuelles

donc l'idée est de sélectionner un compte comptable (vente service intra communautaire) et d'appliquer un rajout d'écritures pour les mouvement qui ont ce compte comptable

**Comment by BebZ** [comment]
![jdv pbl tva cee](https://f.cloud.github.com/assets/3694135/1946834/48fea384-802b-11e3-81e9-095f4522de6f.JPG)

Voilà un exemple, et lorsque je transfère mon JdV au comptable en CSV... bah c la merde.
Ou lorsque je veux faire mes totaux 
achats ventes FR 19,6
achats ventes FR 5.5
achats ventes CEE
 c'est aussi la merde... et y'a pas un comptable qui veut bien faire la "révision" sans pouvoir importer tout proprement...

**Comment by Darkjeff** [comment]
Compte tier Non défini ; il faut les remplir dans les fiches clients
Taux de TVA par défault, pour éviter cela il faut renseigner configuration/Dictionnaire/tva
exemple 
tva 7%  code achat 4456000  code vente 4457000
tva 7% intracomm code acaht 4456100 code vente 4457100
les codes peuvent varier d'un comptable a l'autre, donc se mettre d'accord avec son comptable concernant les comptes a utiliser 

Pour ventiler les achats, appliquer un code en fonction de l'achat
par exemple
6070000 achat de marchandise 
6071000 achat de marchandise intracomm

je rappelle que je ne suis pas comptable, mais comme dit un vieux proverbe, si la montagne ne veut pas venir a toi, c'est a toi de te déplacer jusqu'à la montagne.

**Comment by BebZ** [comment]
> Pour ventiler les achats, appliquer un code en fonction de l'achat
> par exemple
> 6070000 achat de marchandise 
> 6071000 achat de marchandise intracomm

Est-ce qu'on pourrait par exemple (dans les dictionnaires des taxes) > Voir capture ecran
![tva et nouveau taux](https://f.cloud.github.com/assets/3694135/2117807/2ab37c50-90e4-11e3-8a73-635f02bc6502.PNG)

créer des TVA différentes (du même taux ou pas), 
et les renseigner sur les lignes de factures de vente et/ou d'achat (lors de l'enregistrement de celles-ci) afin qu'elles s'additionnent dans le bon compte, et qu'elles soient ventilées vers le bon compte ? 
VENTES FR TVA 20% = 445711
VENTES CEE TVA 0% = 445799

ACHATS FR TVA 20% = 445661
ACHATS CEE TVA 20% = 445699

**Comment by BebZ** [comment]
du nouveau sur la possibilité d'avoir un total des TVA afin de les déclarer en fin de mois ?
et sur la possibilité par le module d'auto liquider ?
