### ISSUE TITLE
Recording an account's root

### ISSUE THREAD

**Issue by BebZ** [Darkjeff/dolibarr_ventilation_compta#55]
![racine de compte fausse aprs enregistrement](https://f.cloud.github.com/assets/3694135/2117525/26ef499c-90d4-11e3-922d-ee059dc2976a.PNG)
![racine de compte](https://f.cloud.github.com/assets/3694135/2117526/26efdcf4-90d4-11e3-9158-98823bec928f.PNG)

APRES ENREGISTREMENT LA RACINE DE COMPTE DEVIENT FAUSSE

**Comment by groolot** [comment]
Par ailleurs, c'est très étonnant la technique utilisée pour afficher la liste des 'Racines de compte' : n'aurait-il pas été plus simple de faire un objet "<select ..>" avec une série d' "<option value=xx>Truc</option>" (en tout cas pour le debuggage ça aurait simplifié grandement).

**Comment by groolot** [comment]
```
--- accountingaccount.class.php-orig    2014-02-15 18:24:15.709208669 +0100
+++ accountingaccount.class.php 2014-02-15 18:36:11.818470451 +0100
@@ -115,7 +115,7 @@
        if (isset ( $this->account_parent ))
            $this->account_parent = trim ( $this->account_parent );
        if (isset ( $this->label ))
-           $this->account_parent = trim ( $this->label );
+           $this->label = trim ( $this->label );
        if (isset ( $this->fk_user_author ))
            $this->fk_user_author = trim ( $this->fk_user_author );
        if (isset ( $this->active ))
@@ -150,9 +150,8 @@
        $sql .= ", " . (! isset ( $this->label ) ? 'NULL' : "'" . $this->db->escape ( $this->label ) . "'");
        $sql .= ", " . $user->id;
        $sql .= ", " . (! isset ( $this->active ) ? 'NULL' : "'" . $this->db->escape ( $this->active ) . "'");
-       
        $sql .= ")";
-       
+
        $this->db->begin ();

        dol_syslog ( get_class ( $this ) . "::create sql=" . $sql, LOG_DEBUG );
```

**Comment by groolot** [comment]
donc c'est clos ?!

**Comment by aspangaro** [comment]
Bonsoir,

Merci pour la correction.

Perso, je réfléchi actuellement à me passer de ces informations. Le numéro de compte, un libellé et éventuellement un champ "catégorie" suffirait. Nous sommes juste partis de ce qui se trouvait dans le core de Dolibarr. Je vais bientôt reprendre le codage sur ce module, nous verrons à ce moment.

**Comment by BebZ** [comment]
A ce que j'ai compris sur le forum : 
Enregistrer les n°s que l'on connait sur le code comptable, sans les derniers zéros, puis paramétrer le module quand on veut exporter avec le nombre de chiffres souhaités (si code 790000 souhaité alors enregistrer 79 et paramétrer sur 6 chiffres l'export) c'est bien ça ? 
Mais en interne, ne surtout pas enregistrer de 000 à la fin ;)
