### ISSUE TITLE
Bad linking between defined account et account suggested for ventilation

### ISSUE THREAD

**Issue by BebZ** [Darkjeff/dolibarr_ventilation_compta#56]
![fourn compte comptable defini mais proposition compte attente](https://f.cloud.github.com/assets/3694135/2117715/f54354ee-90e0-11e3-82a2-387651108e34.PNG)

**Comment by aspangaro** [comment]
Il suffit d'enlever les zéros en bout de code comptable pour rétablir la fonction

**Comment by BebZ** [comment]
Merci ;)
